config/routes.rb
Travel::Application.routes.draw do
  get 'newyork' => 'pages#newyork'

  root :to => 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def action
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-bottom">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <a class="brand" href="/">Livehunter.fm</a>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
       	<ul class="nav">
       		<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "New York", newyork_path %></li>
      	</ul> 
      	<ul class="nav pull-right">
       		<li><%= link_to "Another Link", "#" %></li>
      	</ul>
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  	<title>Livehunter.fm</title>
	  	<%= stylesheet_link_tag    "application", :media => "all" %>
	 	<%= javascript_include_tag "application" %>
	  	<%= csrf_meta_tags %>
	</head>
	<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>

	</div>
	</body>
</html>

app/views/pages/home.html.erb
<h1>Livehunter.fm</h1>
<p>Listen to the bands playing near you</p>
<ul>
	<li><%= link_to "New York", "newyork" %>
</ul>

app/views/pages/newyork.html.erb
require 'songkickr'
remote = Songkickr::Remote.new xZ1mTWcHfu6whfkt
remote.api_key
xZ1mTWcHfu6whfkt

<div class="page-header">
	<h1>New York</h1>

results = remote.events(:query => 'Iron Maiden')

</div>